---
title: "Title: Testing a rapid assessment approach for measuring ecosystem services in urban green alleys"
format: 
  html:
    self-contained: true
    fig-width: 15
    fig-height: 15
    toc: true
    toc-depth: 2
    toc-location: right
knitr:
  opts_knit:
    root.dir: "C:/Users/I_RICHMO/Documents/Repositories/ruelles-vertes"
---

Authors: Marie C Dade, Isabella C. Richmond, Jesse T Rieb, Erin Crockett, Kayleigh Hutt-Taylor, Serena Sinno, Karina Benessaiah, Catherine Destrempes, Jackie Hamilton, Fatemeh Izadi, L. Emily Kroft, Lingshan Li, Michael Paulauskas, Klara J Winkler, Elena M Bennett, Carly D Ziter



```{r, echo = F, eval = T, message = F, warning = F}
source('R/packages.R')
```

## Model Summary Tables



## Temperature

```{r, echo = F, eval = T, fig.width=16, fig.height=10}
tar_load(model_max_temp)

tbl_regression(model_max_temp[[1]]$veg_Avg_max_daily_temp,
               label = list(Groundcover_avg = "Ground Cover (%)", 
                            Midstorey_avg = "Midstory Cover (%)",
                            Canopy_avg = "Canopy Cover (%)",
                            Ruelle_length_m = "Ruelle Length (m)",
                            Ruelle_area_m2 = "Ruelle Area (m2)"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 1a. Average maximum temperature explained by vegetation within the ruelle and ruelle structure")

tbl_regression(model_max_temp[[2]]$Avg_max_daily_temp_50,
               label = list(perveggr = "Vegetation Cover (%)",
                            perbuild = "Building Cover (%)",
                            percan = "Canopy Cover (%)",
                            road_area_m2 = "Road Area (m2)"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 1b. Average maximum temperature explained by surrounding landcover variables within a 50 m buffer surrounding the sensor")

tbl_regression(model_max_temp[[2]]$Avg_max_daily_temp_100,
               label = list(perveggr = "Vegetation Cover (%)",
                            perbuild = "Building Cover (%)",
                            percan = "Canopy Cover (%)",
                            road_area_m2 = "Road Area (m2)"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 1c. Average maximum temperature explained by surrounding landcover variables within a 100 m buffer surrounding the sensor")

tar_load(model_min_temp)

tbl_regression(model_min_temp[[1]]$veg_Avg_min_daily_temp,
               label = list(Groundcover_avg = "Ground Cover (%)", 
                            Midstorey_avg = "Midstory Cover (%)",
                            Canopy_avg = "Canopy Cover (%)",
                            Ruelle_length_m = "Ruelle Length (m)",
                            Ruelle_area_m2 = "Ruelle Area (m2)"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 1d. Average minimum temperature explained by vegetation within the ruelle and ruelle structure")

tbl_regression(model_min_temp[[2]]$Avg_min_daily_temp_50,
               label = list(perveggr = "Vegetation Cover (%)",
                            perbuild = "Building Cover (%)",
                            percan = "Canopy Cover (%)",
                            road_area_m2 = "Road Area (m2)"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 1e. Average minimum temperature explained by surrounding landcover variables within a 50 m buffer surrounding the sensor")

tbl_regression(model_min_temp[[2]]$Avg_min_daily_temp_100,
               label = list(perveggr = "Vegetation Cover (%)",
                            perbuild = "Building Cover (%)",
                            percan = "Canopy Cover (%)",
                            road_area_m2 = "Road Area (m2)"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 1f. Average minimum temperature explained by surrounding landcover variables within a 100 m buffer surrounding the sensor")


```

## Noise

```{r, echo = F, eval = T, fig.width=16, fig.height=10}
tar_load(model_noise)

tbl_regression(model_noise[[1]]$veg_mean_NDSI,
               label = list(Groundcover_avg = "Ground Cover (%)", 
                            Midstorey_avg = "Midstory Cover (%)",
                            Canopy_avg = "Canopy Cover (%)",
                            Ruelle_length_m = "Ruelle Length (m)",
                            Ruelle_area_m2 = "Ruelle Area (m2)"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 2a. Noise explained by vegetation within the ruelle and ruelle structure")

tbl_regression(model_noise[[1]]$aes1_mean_NDSI,
               label = list(PublicArt = "Public Art", 
                            PlayEquipment = "Play Equipment",
                            StructureCondition = "Maintained Structures"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 2b. Noise explained by aesthetic features in group 1")

tbl_regression(model_noise[[1]]$aes2_mean_NDSI,
               label = list(WildlifeSupport = "Wildlife Support", 
                            MaintainedGardens = "Maintained Gardens"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 2c. Noise explained by aesthetic features in group 2")

tbl_regression(model_noise[[2]]$mean_NDSI_50,
               label = list(perveggr = "Vegetation Cover (%)",
                            perbuild = "Building Cover (%)",
                            percan = "Canopy Cover (%)",
                            road_area_m2 = "Road Area (m2)"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 2d. Noise explained by surrounding landcover variables within a 50 m buffer surrounding the sensor")

tbl_regression(model_noise[[2]]$mean_NDSI_100,
               label = list(perveggr = "Vegetation Cover (%)",
                            perbuild = "Building Cover (%)",
                            percan = "Canopy Cover (%)",
                            road_area_m2 = "Road Area (m2)"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 2e. Noise explained by surrounding landcover variables within a 100 m buffer surrounding the sensor")
```

## Floral Habitat

```{r, echo = F, eval = T, fig.width=16, fig.height=10}
tar_load(model_habitat)

tbl_regression(model_habitat[[1]]$veg_Floral_coverage_per_m2,
               label = list(Groundcover_avg = "Ground Cover (%)", 
                            Midstorey_avg = "Midstory Cover (%)",
                            Canopy_avg = "Canopy Cover (%)",
                            Ruelle_length_m = "Ruelle Length (m)",
                            Ruelle_area_m2 = "Ruelle Area (m2)"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 3a. Floral habitat explained by vegetation within the ruelle and ruelle structure")

tbl_regression(model_habitat[[1]]$aes1_Floral_coverage_per_m2,
               label = list(PublicArt = "Public Art", 
                            PlayEquipment = "Play Equipment",
                            StructureCondition = "Maintained Structures"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 3b. Floral habitat explained by aesthetic features in group 1")



tbl_regression(model_habitat[[1]]$aes2_Floral_coverage_per_m2,
               label = list(WildlifeSupport = "Wildlife Support", 
                            MaintainedGardens = "Maintained Gardens"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 3c. Floral habitat explained by aesthetic features in group 2")

```

## Food

```{r, echo = F, eval = T, fig.width=16, fig.height=10}
tar_load(model_food)

tbl_regression(model_food[[1]]$veg_Food_coverage_per_m2,
               label = list(Groundcover_avg = "Ground Cover (%)", 
                            Midstorey_avg = "Midstory Cover (%)",
                            Canopy_avg = "Canopy Cover (%)",
                            Ruelle_length_m = "Ruelle Length (m)",
                            Ruelle_area_m2 = "Ruelle Area (m2)"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 4a. Food provision explained by vegetation within the ruelle and ruelle structure")

tbl_regression(model_food[[1]]$aes1_Food_coverage_per_m2,
               label = list(PublicArt = "Public Art", 
                            PlayEquipment = "Play Equipment",
                            StructureCondition = "Maintained Structures"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 4b. Food provision explained by aesthetic features in group 1")

tbl_regression(model_food[[1]]$aes2_Food_coverage_per_m2,
               label = list(WildlifeSupport = "Wildlife Support", 
                            MaintainedGardens = "Maintained Gardens"),
               intercept = T, estimate_fun = function(x) style_number(x, digits = 3)) %>% 
  as_gt() %>% 
  tab_header(title = "Table 4c. Food provision explained by aesthetic features in group 2")

```


